### ISSUE TITLE
Update Docker version and include buildx

### ISSUE THREAD

**Issue by juventus18** [Sleavely/docker-node-awscli#6]
Can you please update the included docker version and install buildx into the image? I've been using this image to build other images in a CICD pipeline then upload them to an AWS image repo. It has been working great, but the new version of the Nx plugin I'm using requires buildx. There are options to make buildx the default builder, but you don't have to turn it on (for better backward compatibility), I can do so within the CICD container.

Buildx: https://github.com/docker/buildx
Nx Plugin: https://github.com/gperdomor/nx-tools (no actions, just for reference)

**Comment by Sleavely** [comment]
Docker is not included in `sleavely/node-awscli:20.x` (or any earlier versions, AFAIK).

It might be added by your CI environment though; I've used it in Bitbucket Pipelines to build images like this:
```yaml
image: sleavely/node-awscli:20.x

pipelines:
  default:
      - step:
          name: Deploy dev
          services:
            - docker
          script:
            - npx cdk deploy
```
where `cdk` will use Docker to build and push an image to ECR. Most CI providers have equivalent configuration options to expose the Docker daemon.

I don't think adding Docker or its related utilities would benefit the majority of consumers of `sleavely/node-awscli` so I'll close this as "out of scope".
